version: '3'

services:
  php:
    container_name: php
    build: ./docker/php
    volumes:
      - ./app/:/var/www

  nginx:
    image: nginx
    container_name: nginx_host
    ports:
    - 8000:8000
    volumes:
    - ./app/:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: mysql:5.7
    container_name: db_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.conf:/etc/mysql/conf.d/my.conf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
